[[custom_groups]]
name = "ğŸ­ Proxy"
type = "select"
rule = ["[]DIRECT", ".*"]

[[custom_groups]]
name = "ğŸŒ GMedia"
type = "select"
rule = ["[]ğŸ­ Proxy", ".*"]

[[custom_groups]]
name = "ğŸ¤– Ai"
type = "select"
rule = ["[]ğŸ­ Proxy", ".*"]

[[custom_groups]]
name = "ğŸŒ¿ AdBlock"
type = "select"
rule = ["[]REJECT", "[]DIRECT"]

[[custom_groups]]
name = "ğŸ¯ Direct"
type = "select"
rule = ["[]DIRECT", "[]ğŸ­ Proxy"]

[[custom_groups]]
name = "ğŸŒŸ Default"
type = "select"
rule = ["[]ğŸ­ Proxy", "[]DIRECT"]
