[[rulesets]]
group = "ğŸ¯ Direct"
ruleset = "https://github.com/blackmatrix7/ios_rule_script/raw/master/rule/Clash/Lan/Lan.list"

[[rulesets]]
group = "ğŸ¯ Direct"
ruleset = "https://github.com/blackmatrix7/ios_rule_script/raw/master/rule/Clash/Direct/Direct.list"

[[rulesets]]
group = "ğŸŒ¿ AdBlock"
ruleset = "clash-domain:https://raw.githubusercontent.com/TG-Twilight/AWAvenue-Ads-Rule/main/Filters/AWAvenue-Ads-Rule-Clash.yaml"

[[rulesets]]
group = "ğŸŒ GMedia"
ruleset = "https://github.com/blackmatrix7/ios_rule_script/raw/master/rule/Clash/GlobalMedia/GlobalMedia.list"

[[rulesets]]
group = "ğŸ¤– Ai"
ruleset = "https://github.com/blackmatrix7/ios_rule_script/raw/master/rule/Clash/OpenAI/OpenAI.list"

[[rulesets]]
group = "ğŸ¤– Ai"
ruleset = "https://github.com/blackmatrix7/ios_rule_script/raw/master/rule/Clash/Gemini/Gemini.list"

[[rulesets]]
group = "ğŸ¤– Ai"
ruleset = "https://github.com/blackmatrix7/ios_rule_script/raw/master/rule/Clash/Claude/Claude.list"

[[rulesets]]
group = "ğŸ¤– Ai"
ruleset = "https://github.com/blackmatrix7/ios_rule_script/raw/master/rule/Clash/Copilot/Copilot.list"

[[rulesets]]
group = "ğŸ¤– Ai"
ruleset = "https://github.com/blackmatrix7/ios_rule_script/raw/master/rule/Clash/Bing/Bing.list"

[[rulesets]]
group = "ğŸ­ Proxy"
ruleset = "https://github.com/blackmatrix7/ios_rule_script/raw/master/rule/Clash/Google/Google.list"

[[rulesets]]
group = "ğŸ­ Proxy"
ruleset = "https://github.com/blackmatrix7/ios_rule_script/raw/master/rule/Clash/Proxy/Proxy.list"

[[rulesets]]
group = "ğŸ¯ Direct"
ruleset = "https://github.com/blackmatrix7/ios_rule_script/raw/master/rule/Clash/China/China.list"

[[rulesets]]
group = "ğŸ¯ Direct"
ruleset = "clash-ipcidr:https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/cncidr.txt"

[[rulesets]]
group = "ğŸ¯ Direct"
ruleset = "[]GEOIP,CN"

[[rulesets]]
group = "ğŸŒŸ Default"
ruleset = "[]MATCH"
